version: '2'

services:
  drone-server:
    image: 'drone/drone:latest'
    ports:
      - '8000'
    volumes:
      - /var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GITHUB=true
      - 'DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}'
      - 'DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}'
      - 'DRONE_SECRET=${DRONE_SECRET}'
  drone-agent:
    image: 'drone/drone:latest'
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock
    environment:
      - 'DRONE_SERVER=ws://drone-server:8000/ws/broker'
      - 'DRONE_SECRET=${DRONE_SECRET}'
